name: qnn-310
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.12.1=pyhcf101f3_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhcf101f3_2
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attrs=21.4.0=pyhd8ed1ab_0
  - autograd=1.8.0=pyhd8ed1ab_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cirq=1.4.1=pyh29332c3_0
  - cirq-aqt=1.4.1=pyh29332c3_0
  - cirq-ionq=1.4.1=pyh29332c3_0
  - cirq-pasqal=1.4.1=pyh29332c3_0
  - cirq-rigetti=1.4.1=pyh29332c3_0
  - cirq-web=1.4.1=pyh29332c3_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cryptography=39.0.0=py310h65dfdc0_0
  - cycler=0.12.1=pyhcf101f3_2
  - deprecated=1.3.1=pyhd8ed1ab_0
  - duet-python=0.2.9=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.7.0=py310h9548a50_0
  - gast=0.7.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - google-api-core=2.11.1=pyhd8ed1ab_0
  - google-api-core-grpc=2.11.1=hd8ed1ab_0
  - google-auth=2.47.0=pyhcf101f3_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - googleapis-common-protos=1.63.1=pyhd8ed1ab_0
  - grpc-cpp=1.43.2=h9e046d8_3
  - grpcio-status=1.41.1=pyhd8ed1ab_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.3.0=pyhcf101f3_0
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=0.16.3=pyhd8ed1ab_0
  - httpx=0.23.3=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=4.13.0=pyha770c72_0
  - iso8601=1.1.0=pyhd8ed1ab_0
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - js2py=0.74=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.20.1=hf9c8cef_0
  - lark=0.11.3=pyhd8ed1ab_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=h4751f2c_7
  - liblapack=3.11.0=5_h47877c9_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.19.6=h3eb15da_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.3.0=h0fcbabc_4
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.2.13=h4ab18f5_6
  - markdown=3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.1=py310h68603db_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310h03d9f68_1
  - multidict=6.7.0=py310h3406613_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=1.26.4=py310hb13e2d6_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - olefile=0.47=pyhd8ed1ab_1
  - openjpeg=2.5.0=h7d73246_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.3.3=py310h0158d43_2
  - pennylane=0.37.0=py310hff52083_0
  - pennylane-core=0.37.0=py310hff52083_0
  - pillow=8.4.0=py310h07f4688_0
  - pip=25.3=pyhc872135_0
  - propcache=0.3.1=py310h89163eb_0
  - proto-plus=1.27.0=pyhd8ed1ab_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=1.10.22=pyh3cfb1c2_0
  - pyjsparser=2.7.1=pyhd8ed1ab_2
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyquil=4.14.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.13=h7a1cb2a_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-gil=3.10.19=hd8ed1ab_2
  - python-rapidjson=1.23=py310hea6c23e_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyzmq=27.1.0=py310h4f33d48_0
  - qcs-api-client=0.21.5=pyhd8ed1ab_0
  - qcs-sdk-python=0.19.3=py310hf71b8c6_0
  - qhull=2020.2=h434a139_5
  - quil=0.11.2=py310h61a050e_1
  - re2=2022.02.01=h9c3ff4c_0
  - readline=8.3=hc2a1206_0
  - regex=2025.11.3=py310h7c4b9e2_1
  - requests=2.32.5=pyhcf101f3_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - retrying=1.4.2=pyhe01879c_0
  - rfc3339=6.2=pyhd8ed1ab_2
  - rfc3986=1.5.0=pyhd8ed1ab_0
  - rpcq=3.11.0=pyhd8ed1ab_2
  - rsa=4.9.1=pyhd8ed1ab_0
  - ruamel.yaml=0.19.1=pyhcf101f3_0
  - ruamel.yaml.clib=0.2.15=py310h139afa4_1
  - rustworkx=0.17.1=py310h1570de5_3
  - scikit-learn=1.7.2=py310h228f341_0
  - semantic_version=2.10.0=pyhd8ed1ab_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=hdb0a2a9_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.51.1=he0a8d7e_0
  - sympy=1.14.0=pyh2585a3b_105
  - tenacity=8.5.0=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow-cpu=2.8.0=cpu_py310h718b53a_0
  - tensorflow-estimator=2.8.0=cpu_py310had6d012_0
  - termcolor=3.3.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - toml=0.10.2=pyhcf101f3_3
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-deprecated=1.3.1.20251101=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20251115=pyhd8ed1ab_0
  - types-retry=0.9.9.20250322=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - werkzeug=3.1.5=pyhcf101f3_0
  - wheel=0.45.1=py310h06a4308_0
  - wrapt=1.17.3=py310h7c4b9e2_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yarl=1.22.0=py310h3406613_0
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310h7c4b9e2_3
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - autoray==0.6.11
      - cirq-core==1.3.0
      - cirq-google==1.3.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - keras==3.12.0
      - libclang==18.1.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.1.0
      - optree==0.18.0
      - protobuf==4.25.8
      - pygments==2.19.2
      - rich==14.2.0
      - scipy==1.12.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-quantum==0.7.4
      - tf-keras==2.16.0
prefix: /NFSHOME/eobeng/miniconda3/envs/qnn-310
